export const alabamaBuyboxes = [
  {
    city: "auburn",
    county: "russelllee",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "auburn",
    county: "russelllee",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "decatur",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1970,
    sqftMin: 1000,
    arvPercentMax: 72.5,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "huntsville",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1100,
    arvPercentMax: 75,
    maxRehabCost: 71666.67,
    maxPrice: 291666.67,
    hoa: false,
  },
  {
    city: "jacksonville",
    county: "jeffersonst. clairblountshelby",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 266666.67,
    hoa: false,
  },
  {
    city: "mobile",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 73.75,
    maxRehabCost: 74999.75,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "montgomery",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 424000,
    hoa: false,
  },
  {
    city: "phenix city",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "tuscaloosa",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 900,
    arvPercentMax: 70,
    maxRehabCost: 50000,
    maxPrice: 280000,
    hoa: false,
  },
];
