export const alabamaBuyboxes = [
  {
    city: "auburn",
    county: "lee", // ✅ Auburn is in Lee County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "decatur",
    county: "morgan", // ✅ Decatur is in Morgan County (small portion in Limestone, but Morgan is primary)
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1970,
    sqftMin: 1000,
    arvPercentMax: 72.5,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "huntsville",
    county: "madison", // ✅ Huntsville is in Madison County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1100,
    arvPercentMax: 75,
    maxRehabCost: 71666.67,
    maxPrice: 291666.67,
    hoa: false,
  },
  {
    city: "jacksonville",
    county: "calhoun", // ✅ Jacksonville is in Calhoun County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 266666.67,
    hoa: false,
  },
  {
    city: "mobile",
    county: "mobile", // ✅ Mobile is in Mobile County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 73.75,
    maxRehabCost: 74999.75,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "montgomery",
    county: "montgomery", // ✅ Montgomery is in Montgomery County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 424000,
    hoa: false,
  },
  {
    city: "phenix city",
    county: "russell", // ✅ Phenix City is primarily in Russell County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "tuscaloosa",
    county: "tuscaloosa", // ✅ Tuscaloosa is in Tuscaloosa County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 900,
    arvPercentMax: 70,
    maxRehabCost: 50000,
    maxPrice: 280000,
    hoa: false,
  },
];
