export const arizonaBuyboxes = [
  {
    city: "maricopa",
    county: "maricopapinalpimacoconino",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 73.33,
    maxRehabCost: 100000,
    maxPrice: 516666.67,
    hoa: false,
  },
  {
    city: "mesa",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 2,
    yearBuiltMin: 1960,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 900000,
    hoa: false,
  },
  {
    city: "phoenix",
    county: "maricopapinalpimasanta cruzgreenleecochisenavajococoninola pazapachemohaveyavapai",
    propertyType: "single family",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 4000,
    arvPercentMax: 73.43,
    maxRehabCost: 76170.83,
    maxPrice: 313478.84,
    hoa: true,
  },
  {
    city: "tucson",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1970,
    sqftMin: 1100,
    arvPercentMax: 75,
    maxRehabCost: 57500,
    maxPrice: 415000,
    hoa: false,
  },
];
