export const californiaBuyboxes = [
  {
    city: "berkeley",
    county: "alameda",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 900,
    arvPercentMax: 60,
    maxRehabCost: 40000,
    maxPrice: 150000,
    hoa: false,
  },
  {
    city: "bonsall",
    county: "san diego",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 30000,
    maxPrice: 900000,
    hoa: false,
  },
  {
    city: "coachella",
    county: "riverside",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 800000,
    hoa: false,
  },
  {
    city: "fresno",
    county: "fresno",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 73.33,
    maxRehabCost: 60000,
    maxPrice: 500000,
    hoa: false,
  },
  {
    city: "hollywood",
    county: "los angeles",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 400000,
    hoa: false,
  },
  {
    city: "jacksonville",
    county: "san bernardino",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 400000,
    hoa: false,
  },
  {
    city: "lancaster",
    county: "los angeles",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 72.5,
    maxRehabCost: 52500,
    maxPrice: 600000,
    hoa: false,
  },
  {
    city: "long beach",
    county: "los angeles",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 30000,
    maxPrice: 900000,
    hoa: false,
  },
  {
    city: "los angeles",
    county: "los angeles",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 3500,
    arvPercentMax: 73.18,
    maxRehabCost: 76653.39,
    maxPrice: 333804.74,
    hoa: true,
  },
  {
    city: "malibu",
    county: "los angeles",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "napa",
    county: "napa",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 30000,
    maxPrice: 900000,
    hoa: false,
  },
  {
    city: "pasadena",
    county: "los angeles",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1300,
    sqftMax: 2100,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 100000,
    hoa: false,
  },
  {
    city: "pittsburg",
    county: "contra costa",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "riverside",
    county: "riverside",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "sacramento",
    county: "sacramento",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 74,
    maxRehabCost: 66000,
    maxPrice: 560000,
    hoa: false,
  },
  {
    city: "san bernardino",
    county: "san bernardino",
    propertyType: "single family",
    bedMin: 4,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "san diego",
    county: "san diego",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 72.5,
    maxRehabCost: 74999.5,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "san francisco",
    county: "san francisco",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 96428.57,
    maxPrice: 485714.29,
    hoa: false,
  },
  {
    city: "san joaquin",
    county: "san joaquin",
    propertyType: "single family",
    bedMin: 4,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "san jose",
    county: "santa clara",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 30000,
    maxPrice: 900000,
    hoa: false,
  },
  {
    city: "santa barbara",
    county: "santa barbara",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "vallejo",
    county: "solano",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
];
