export const floridaBuyboxes = [
  {
    city: "cape coral",
    county: "lee",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 73.33,
    maxRehabCost: 66666.67,
    maxPrice: 333333.33,
    hoa: false,
  },
  {
    city: "daytona beach",
    county: "volusia",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 250000,
    hoa: false,
  },
  {
    city: "fort lauderdale",
    county: "broward",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "fort myers",
    county: "lee",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1970,
    sqftMin: 1100,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 517500,
    hoa: false,
  },
  {
    city: "gainesville",
    county: "alachua",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 73.75,
    maxRehabCost: 75000,
    maxPrice: 293750,
    hoa: false,
  },
  {
    city: "hillsborough county",
    county: "hillsborough",
    propertyType: "single family",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "jacksonville",
    county: "duval",
    propertyType: "single familymultifamily",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 4000,
    arvPercentMax: 73.56,
    maxRehabCost: 75914.06,
    maxPrice: 308530.44,
    hoa: true,
  },
  {
    city: "lakeland",
    county: "polk",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 50000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "lehigh acres",
    county: "lee",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 50000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "miami",
    county: "miami-dade",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 72.88,
    maxRehabCost: 71875,
    maxPrice: 259375,
    hoa: false,
  },
  {
    city: "naples",
    county: "collier",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 72.5,
    maxRehabCost: 62500,
    maxPrice: 337500,
    hoa: false,
  },
  {
    city: "ocala",
    county: "marion",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 50000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "orlando",
    county: "orange",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 283000,
    hoa: false,
  },
  {
    city: "palm bay",
    county: "brevard",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1970,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 361250,
    hoa: false,
  },
  {
    city: "panama city",
    county: "bay",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "panama city beach",
    county: "bay",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 283333.33,
    hoa: false,
  },
  {
    city: "pensacola",
    county: "escambia",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 600000,
    hoa: false,
  },
  {
    city: "polk city",
    county: "polk",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "port charlotte",
    county: "charlotte",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 50000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "port saint lucie",
    county: "st. lucie",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 50000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "saint augustine",
    county: "st. johns",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 500000,
    hoa: false,
  },
  {
    city: "sarasota",
    county: "sarasota",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "tallahassee",
    county: "leon",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1100,
    arvPercentMax: 75,
    maxRehabCost: 100000,
    maxPrice: 175000,
    hoa: false,
  },
  {
    city: "tampa",
    county: "hillsborough",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 900,
    sqftMax: 3000,
    arvPercentMax: 71.42,
    maxRehabCost: 115094.34,
    maxPrice: 339792.45,
    hoa: false,
  },
];
