export const georgiaBuyboxes = [
  {
    city: "acworth",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "atlanta",
    county:
      "fultoncobbclaytonhenrypauldinggwinnettdekalbhallchathamcherokeeforsythrichmondlowndesthomasbrookscookecholsgradycolquittlanierclinchdouglasfayettedadewalkercatoosa",
    propertyType: "single familysingle propertymultifamily",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 4500,
    arvPercentMax: 73.23,
    maxRehabCost: 74983.5,
    maxPrice: 313085.79,
    hoa: true,
  },
  {
    city: "augusta",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "columbus",
    county: "muscogeeharris",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 316666.67,
    hoa: false,
  },
  {
    city: "decatur",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 80000,
    maxPrice: 200000,
    hoa: false,
  },
  {
    city: "kennesaw",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "lawrenceville",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "macon",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 195000,
    hoa: false,
  },
  {
    city: "marietta",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "powder springs",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "ringgold",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 200000,
    hoa: false,
  },
  {
    city: "savannah",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 316666.67,
    hoa: false,
  },
  {
    city: "smyrna",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "valdosta",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
];
