export const kansasBuyboxes = [
  {
    city: "kansas city",
    county: "johnsonwyandottejacksonclayleavenworth",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1944,
    sqftMin: 900,
    arvPercentMax: 73.75,
    maxRehabCost: 75000,
    maxPrice: 376249.75,
    hoa: false,
  },
  {
    city: "wichita",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 250000,
    hoa: false,
  },
];
