export const louisianaBuyboxes = [
  {
    city: "baton rouge",
    county: "east baton rouge", // ✅
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 74.44,
    maxRehabCost: 75000,
    maxPrice: 377777.78,
    hoa: false,
  },
  {
    city: "bossier city",
    county: "bossier", // ✅
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "denham springs",
    county: "livingston", // ✅
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "houma",
    county: "terrebonne", // ✅
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "jefferson",
    county: "jefferson", // ✅
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 74999,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "kenner",
    county: "jefferson", // ✅
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "lafayette",
    county: "lafayette", // ✅
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "lake charles",
    county: "calcasieu", // ✅
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "metairie",
    county: "jefferson", // ✅
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "new orleans",
    county: "orleans", // ✅
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 500,
    arvPercentMax: 71.27,
    maxRehabCost: 78830.2,
    maxPrice: 307765.84,
    hoa: true,
  },
  {
    city: "shreveport",
    county: "caddo", // ✅
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
];
