export const marylandBuyboxes = [
  {
    city: "baltimore",
    county: "montgomeryprince george'sbaltimoreanne arundelhowardfrederickharfordcharlescarrollwashingtoncecilkent",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 500,
    sqftMax: 3500,
    arvPercentMax: 72.93,
    maxRehabCost: 78243.46,
    maxPrice: 304081.04,
    hoa: true,
  },
  {
    city: "bowie",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "brandywine",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "columbia",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 450000,
    hoa: false,
  },
  {
    city: "ellicott city",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "frederick",
    county: "carrollfrederickbaltimoreharfordanne arundel",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1940,
    sqftMin: 1000,
    arvPercentMax: 66,
    maxRehabCost: 83333.33,
    maxPrice: 266666.67,
    hoa: false,
  },
  {
    city: "glen burnie",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "hagerstown",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "laurel",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "upper marlboro",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "white marsh",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
];
