export const marylandBuyboxes = [
  {
    city: "baltimore",
    county: "baltimore", // ✅ Baltimore City and Baltimore County exist, defaulting to county for consistency
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 500,
    sqftMax: 3500,
    arvPercentMax: 72.93,
    maxRehabCost: 78243.46,
    maxPrice: 304081.04,
    hoa: true,
  },
  {
    city: "bowie",
    county: "prince george's", // ✅ Bowie is in Prince George's County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "brandywine",
    county: "prince george's", // ✅ Brandywine is in Prince George's County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "columbia",
    county: "howard", // ✅ Columbia is in Howard County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 450000,
    hoa: false,
  },
  {
    city: "ellicott city",
    county: "howard", // ✅ Ellicott City is in Howard County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "frederick",
    county: "frederick", // ✅ Frederick is in Frederick County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1940,
    sqftMin: 1000,
    arvPercentMax: 66,
    maxRehabCost: 83333.33,
    maxPrice: 266666.67,
    hoa: false,
  },
  {
    city: "glen burnie",
    county: "anne arundel", // ✅ Glen Burnie is in Anne Arundel County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "hagerstown",
    county: "washington", // ✅ Hagerstown is in Washington County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "laurel",
    county: "prince george's", // ✅ Laurel spans multiple counties, most populous in Prince George's
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "upper marlboro",
    county: "prince george's", // ✅ Upper Marlboro is in Prince George's County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "white marsh",
    county: "baltimore", // ✅ White Marsh is in Baltimore County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
];
