export const massachusettsBuyboxes = [
  {
    city: "lowell",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "springfield",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 500,
    arvPercentMax: 71.13,
    maxRehabCost: 79375.44,
    maxPrice: 310227.15,
    hoa: true,
  },
];
