export const missouriBuyboxes = [
  {
    city: "florissant",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "independence",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 100000,
    maxPrice: 200000,
    hoa: false,
  },
  {
    city: "jackson",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 900,
    arvPercentMax: 70,
    maxRehabCost: 25000,
    maxPrice: 80000,
    hoa: false,
  },
  {
    city: "kansas city",
    county: "claychristianjasperplattegreenest. charlesboonejacksonst. louismississippijohnsoncassvolusia",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 3500,
    arvPercentMax: 72.84,
    maxRehabCost: 75185.25,
    maxPrice: 301504.57,
    hoa: true,
  },
  {
    city: "saint louis",
    county: "st. louisst. charles",
    propertyType: "single familysingle family.",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1900,
    sqftMin: 100,
    arvPercentMax: 75,
    maxRehabCost: 63730.77,
    maxPrice: 201355.38,
    hoa: false,
  },
  {
    city: "saint louis county",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 900,
    arvPercentMax: 70,
    maxRehabCost: 33333.33,
    maxPrice: 326666.67,
    hoa: false,
  },
  {
    city: "springfield",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1949,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 216666.67,
    hoa: false,
  },
];
