export const newyorkBuyboxes = [
  {
    city: "binghamton",
    county: "broome", // ✅ Binghamton is in Broome County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "brooklyn",
    county: "kings", // ✅ Brooklyn is a borough of NYC, officially Kings County
    propertyType: "single family",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 3500,
    arvPercentMax: 73.74,
    maxRehabCost: 76623.17,
    maxPrice: 309083.73,
    hoa: true,
  },
  {
    city: "buffalo",
    county: "erie", // ✅ Buffalo is in Erie County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1920,
    sqftMin: 900,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "nassau",
    county: "nassau", // ✅ If referring to Nassau County directly
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "new york",
    county: "new york", // ✅ Manhattan borough is New York County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1929,
    sqftMin: 1000,
    arvPercentMax: 71.28,
    maxRehabCost: 83459.62,
    maxPrice: 341025.64,
    hoa: false,
  },
  {
    city: "rochester",
    county: "monroe", // ✅ Rochester is in Monroe County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 110000,
    hoa: false,
  },
];
