export const northcarolinaBuyboxes = [
  {
    city: "charlotte",
    county: "mecklenburg", // ✅ Charlotte is in Mecklenburg County
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 4000,
    arvPercentMax: 73.37,
    maxRehabCost: 75893.44,
    maxPrice: 306102.52,
    hoa: true,
  },
  {
    city: "durham",
    county: "durham", // ✅ Durham is in Durham County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 900,
    sqftMax: 3000,
    arvPercentMax: 57.5,
    maxRehabCost: 57500,
    maxPrice: 275000,
    hoa: false,
  },
  {
    city: "greensboro",
    county: "guilford", // ✅ Greensboro is in Guilford County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 66250,
    maxPrice: 263500,
    hoa: false,
  },
  {
    city: "raleigh",
    county: "wake", // ✅ Raleigh is in Wake County
    propertyType: "single family",
    foundation: "slab",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 73.85,
    maxRehabCost: 64615.38,
    maxPrice: 390769.23,
    hoa: false,
  },
];
