export const ohioBuyboxes = [
  {
    city: "akron",
    county: "summitstarktuscarawas",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1900,
    sqftMin: 100,
    sqftMax: 2000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 244375,
    hoa: false,
  },
  {
    city: "cincinnati",
    county: "hamiltonbutler",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1900,
    sqftMin: 800,
    arvPercentMax: 74.5,
    maxRehabCost: 74000,
    maxPrice: 281250,
    hoa: false,
  },
  {
    city: "cleveland",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 750,
    sqftMax: 2500,
    arvPercentMax: 71.29,
    maxRehabCost: 73111.11,
    maxPrice: 280666.67,
    hoa: false,
  },
  {
    city: "columbus",
    county: "butlersummitlucascuyahogafranklinmahoninghamiltonhancockmontgomeryputnam",
    propertyType: "single family",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 4000,
    arvPercentMax: 73.3,
    maxRehabCost: 75102.19,
    maxPrice: 304411.56,
    hoa: true,
  },
  {
    city: "dayton",
    county: "franklincuyahogalakelucasmadisonfairfieldunionpickawayhamiltonfayette",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 750,
    sqftMax: 3500,
    arvPercentMax: 74.69,
    maxRehabCost: 75970.87,
    maxPrice: 286504.85,
    hoa: true,
  },
  {
    city: "franklin",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "maple heights",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "mason",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "springfield",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1949,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "toledo",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 264000,
    hoa: false,
  },
  {
    city: "youngstown",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
];
