export const tennesseeBuyboxes = [
  {
    city: "bartlett",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 50000,
    maxPrice: 375000,
    hoa: false,
  },
  {
    city: "chattanooga",
    county: "tulsa",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 73.33,
    maxRehabCost: 75000,
    maxPrice: 266666.67,
    hoa: false,
  },
  {
    city: "knoxville",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 63333.33,
    maxPrice: 343333.33,
    hoa: false,
  },
  {
    city: "memphis",
    county: "shelbytiptonrutherforddavidsonwashingtonwilliamsonknoxdyerwilsonsumnerhamiltonmontgomerymaricopasan joaquin",
    propertyType: "single family, multifamily",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 3500,
    arvPercentMax: 73.14,
    maxRehabCost: 76752.76,
    maxPrice: 314280.42,
    hoa: true,
  },
  {
    city: "middle valley",
    county: "wilsondavidsonsumnerwilliamsoncumberlandputnamrutherford",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "murfreesboro",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "nashville",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    sqftMax: 4000,
    arvPercentMax: 75,
    maxRehabCost: 72989.6,
    maxPrice: 331000,
    hoa: false,
  },
];
