export const texasBuyboxes = [
  {
    city: "amarillo",
    county: "potter", // ✅ Amarillo is primarily in Potter County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    sqftMax: 3500,
    arvPercentMax: 72.5,
    minSchoolScore: 15,
    maxRehabCost: 80000,
    maxPrice: 400000,
    hoa: false,
  },
  {
    city: "arlington",
    county: "tarrant", // ✅ Arlington is in Tarrant County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    sqftMax: 3500,
    arvPercentMax: 72.5,
    minSchoolScore: 15,
    maxRehabCost: 80000,
    maxPrice: 400000,
    hoa: false,
  },
  {
    city: "austin",
    county: "travis", // ✅ Austin is in Travis County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 900,
    sqftMax: 3500,
    arvPercentMax: 74.29,
    minSchoolScore: 15,
    maxRehabCost: 90000,
    maxPrice: 384285.71,
    hoa: false,
  },
  {
    city: "baytown",
    county: "harris", // ✅ Baytown is primarily in Harris County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "beaumont",
    county: "jefferson", // ✅ Beaumont is in Jefferson County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "cleveland",
    county: "liberty", // ✅ Cleveland, TX is in Liberty County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1990,
    sqftMin: 1000,
    sqftMax: 3500,
    arvPercentMax: 70,
    minSchoolScore: 15,
    maxRehabCost: 85000,
    maxPrice: 500000,
    hoa: false,
  },
  {
    city: "dallas",
    county: "dallas", // ✅ Dallas is in Dallas County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 900,
    sqftMax: 3500,
    arvPercentMax: 71.91,
    minSchoolScore: 15,
    maxRehabCost: 74818.18,
    maxPrice: 323690.91,
    hoa: false,
  },
  {
    city: "el paso",
    county: "el paso", // ✅ El Paso is in El Paso County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    sqftMax: 3500,
    arvPercentMax: 71.67,
    minSchoolScore: 15,
    maxRehabCost: 81666.67,
    maxPrice: 433333.33,
    hoa: false,
  },
  {
    city: "fort worth",
    county: "tarrant", // ✅ Fort Worth is in Tarrant County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 700,
    sqftMax: 3500,
    arvPercentMax: 71.25,
    minSchoolScore: 15,
    maxRehabCost: 76250,
    maxPrice: 400000,
    hoa: false,
  },
  {
    city: "hollywood park",
    county: "bexar", // ✅ Hollywood Park is in Bexar County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1950,
    sqftMin: 1200,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "houston",
    county: "harris", // ✅ Houston is in Harris County (may extend to Fort Bend, but Harris is primary)
    propertyType: "single family, single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 4000,
    arvPercentMax: 73.72,
    maxRehabCost: 76071.37,
    maxPrice: 309621.82,
    hoa: true,
  },
  {
    city: "richmond",
    county: "fort bend", // ✅ Richmond is in Fort Bend County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "spring",
    county: "harris", // ✅ Spring is in unincorporated Harris County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1990,
    sqftMin: 1000,
    sqftMax: 3500,
    arvPercentMax: 70,
    minSchoolScore: 15,
    maxRehabCost: 85000,
    maxPrice: 500000,
    hoa: false,
  },
  {
    city: "sugar land",
    county: "fort bend", // ✅ Sugar Land is in Fort Bend County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 2,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 50000,
    maxPrice: 350000,
    hoa: false,
  },
];
