export const washingtonBuyboxes = [
  {
    city: "king county",
    county: "king", // ✅ This entry already references the county itself
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1930,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 50000,
    maxPrice: 350000,
    hoa: false,
  },
  {
    city: "seattle",
    county: "king", // ✅ Seattle is in King County
    propertyType: "single family, single property",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 700,
    sqftMax: 3500,
    arvPercentMax: 73.31,
    maxRehabCost: 76726.52,
    maxPrice: 309013.23,
    hoa: true,
  },
  {
    city: "spokane",
    county: "spokane", // ✅ Spokane is in Spokane County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "vancouver",
    county: "clark", // ✅ Vancouver, WA is in Clark County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "vashon",
    county: "king", // ✅ Vashon Island is part of unincorporated King County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
];
