export const westvirginiaBuyboxes = [
  {
    city: "charleston",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1940,
    sqftMin: 1000,
    arvPercentMax: 70,
    maxRehabCost: 81250,
    maxPrice: 275000,
    hoa: false,
  },
  {
    city: "clarksburg",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 80000,
    hoa: false,
  },
];
