export const wisconsinBuyboxes = [
  {
    city: "appleton",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 299999,
    hoa: false,
  },
  {
    city: "fond du lac",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 500,
    sqftMax: 3500,
    arvPercentMax: 72.98,
    maxRehabCost: 78588.47,
    maxPrice: 310735.25,
    hoa: true,
  },
  {
    city: "green bay",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "janesville",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "kenosha",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "madison",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 71.5,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "milwaukee",
    county: "milwaukeewaukeshaozaukee",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 961,
    arvPercentMax: 73.67,
    maxRehabCost: 78326.44,
    maxPrice: 292222.22,
    hoa: false,
  },
  {
    city: "racine",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "waukesha",
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "wausau",
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 71.5,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "west allis",
    propertyType: "single family",
    foundation: "slab",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
];
