export const wisconsinBuyboxes = [
  {
    city: "appleton",
    county: "outagamie", // ✅ Appleton is primarily in Outagamie County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 299999,
    hoa: false,
  },
  {
    city: "fond du lac",
    county: "fond du lac", // ✅ Fond du Lac is in Fond du Lac County
    propertyType: "single family",
    foundation: "slab",
    bedMin: 1,
    bathMin: 1,
    yearBuiltMin: 1910,
    sqftMin: 500,
    sqftMax: 3500,
    arvPercentMax: 72.98,
    maxRehabCost: 78588.47,
    maxPrice: 310735.25,
    hoa: true,
  },
  {
    city: "green bay",
    county: "brown", // ✅ Green Bay is in Brown County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "janesville",
    county: "rock", // ✅ Janesville is in Rock County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "kenosha",
    county: "kenosha", // ✅ Kenosha is in Kenosha County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "madison",
    county: "dane", // ✅ Madison is in Dane County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 71.5,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "milwaukee",
    county: "milwaukee", // ✅ Milwaukee is in Milwaukee County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 961,
    arvPercentMax: 73.67,
    maxRehabCost: 78326.44,
    maxPrice: 292222.22,
    hoa: false,
  },
  {
    city: "racine",
    county: "racine", // ✅ Racine is in Racine County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 75,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "waukesha",
    county: "waukesha", // ✅ Waukesha is in Waukesha County
    propertyType: "single family",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "wausau",
    county: "marathon", // ✅ Wausau is in Marathon County
    propertyType: "single family",
    bedMin: 2,
    bathMin: 1,
    yearBuiltMin: 1950,
    sqftMin: 1000,
    arvPercentMax: 71.5,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
  {
    city: "west allis",
    county: "milwaukee", // ✅ West Allis is in Milwaukee County
    propertyType: "single family",
    foundation: "slab",
    bedMin: 3,
    bathMin: 1,
    sqftMin: 1000,
    arvPercentMax: 68,
    maxRehabCost: 75000,
    maxPrice: 300000,
    hoa: false,
  },
];
